"""Builds a static GitHub Pages report summarizing the latest trained model.

Reads data/chl_model.pkl (the full training artifact — SHAP, LOOCV results,
classifier_eval) and data/chl_predictions.csv, and writes a single
self-contained docs/index.html: dataset size, which model candidates were
evaluated and which won each stage, AUPRC/F1 (classifier) and MAE
(regressor), SHAP feature-importance bar charts for every candidate model,
and the top-15 suspect cards.

The report body itself lives in report_content.py, shared with
streamlit_app.py's landing page so both surfaces always show identical
numbers/charts — this module only adds the standalone-page wrapper
(title, footer, links) and writes the file.

Enable Pages once in the repo's Settings -> Pages -> "Deploy from a branch",
source = main, folder = /docs. Re-run this after every retrain:

    python -m model.train
    python -m model.predict
    python -m scripts.build_report
"""

import logging
import os
import pickle
from datetime import datetime, timezone
from glob import glob

import pandas as pd

from report_content import REPORT_CSS, render_report_sections

logger = logging.getLogger(__name__)

DATA_DIR = "data"
MODEL_PATH = os.path.join(DATA_DIR, "chl_model.pkl")
PREDICTIONS_PATH = os.path.join(DATA_DIR, "chl_predictions.csv")
DOCS_DIR = "docs"
OUTPUT_PATH = os.path.join(DOCS_DIR, "index.html")

# Filled in once the app is deployed — used for the "rate these cards
# yourself" footer link. Update after your first Streamlit Cloud deploy.
STREAMLIT_APP_URL = "https://share.streamlit.io/"


def _latest_per_card_df() -> pd.DataFrame:
    candidates = sorted(glob(os.path.join(DATA_DIR, "chl_dataset_per_card_*.pkl")))
    if not candidates:
        raise FileNotFoundError("No per_card dataset found. Run pipeline.py first.")
    with open(candidates[-1], "rb") as f:
        return pickle.load(f)


def build(model_path: str = MODEL_PATH, predictions_path: str = PREDICTIONS_PATH) -> None:
    logging.basicConfig(level=logging.INFO)

    with open(model_path, "rb") as f:
        artifact = pickle.load(f)
    predictions = pd.read_csv(predictions_path)
    per_card = _latest_per_card_df()

    sections_html = render_report_sections(artifact, predictions, per_card)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html_doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CHL Points Bot - Model Report</title>
{REPORT_CSS}
<style>
  body {{ margin: 0; background: var(--surface-page, #f9f9f7); }}
  main {{ max-width: 960px; margin: 0 auto; padding: 32px 20px 64px; }}
  footer {{ margin-top: 48px; color: var(--text-muted, #898781); font-size: 13px; }}
</style>
</head>
<body class="viz-root">
<main>
  <h1>🎯 CHL Points Bot - Model Report</h1>
  <p class="subtitle">10-point Canadian Highlander (CHL) points model - evaluation summary. Generated {generated_at}.</p>
  {sections_html}
  <footer>
    Generated by <code>scripts/build_report.py</code> from <code>data/chl_model.pkl</code> and
    <code>data/chl_predictions.csv</code>. Source: <a href="https://github.com/BIG-TRUCK/points_bot">BIG-TRUCK/points_bot</a>.
    Rate any of these cards yourself in the <a href="{STREAMLIT_APP_URL}">companion Streamlit app</a>.
  </footer>
</main>
</body>
</html>
"""

    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(html_doc)
    logger.info(f"Report written to {OUTPUT_PATH}")


if __name__ == "__main__":
    build()
